spring:
    application:
        name: donation-api
    
    datasource:
        url: jdbc:h2:mem:donatioAPI
        driverClassName: org.h2.Driver
        username: izaias
        password: izaias
    
    jpa:
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true
    
    sql:
        init:
            mode: always
    
    h2:
        console:
            enabled: true
            path: /h2-console
            
server:
    port: 8000